### ISSUE TITLE
Should 'froala-wysiwyg-editor' dependency be in devDependencies?

### ISSUE THREAD

**Issue by mike183** [froala/ember-froala-editor#12]
Currently, the 'froala-wysiwyg-editor' bower dependency is within the devDependencies section of the bower.json file.

This forces users of this add-on to add the 'froala-wysiwyg-editor' bower dependency to their main applications bower.json file in order to have the froala editor itself installed when running `bower install` from the root of their Ember-CLI application.

Should the 'froala-wysiwyg-editor' dependency be moved from devDependencies into dependencies so that it is installed automatically?

Happy to submit a PR if so.

**Comment by Panman8201** [comment]
Nope, the [addon blueprint will install the dep into the _projects_ `bower.json` dependencies](https://github.com/froala/ember-froala-editor/blob/v2.3.4/blueprints/ember-froala-editor/index.js#L15). It's in the addon's devDependencies so that it's available while building the documentation.

**Comment by mike183** [comment]
I think I see the reason now, I was under the impression that when you installed an ember add-on, the dependencies listed under 'dependencies' in the add-ons bower.json file were also installed but this doesn't look to be the case.

I was hoping that this would also resolve the issue of requiring the user to manually update their bower.json file whenever 'froala-wysiwyg-editor' is updated. Currently when the 'froala-wysiwyg-editor' dependency version is updated in 'ember-froala-editor', the change isn't reflected in the users application until they update it themselves.

Not sure there is a great deal that can be done about that though...closing.

**Comment by Panman8201** [comment]
Actually, I think it's possible to make it work that way. I've just always wanted to manage the deps via project rather than the addon, but since versioning lines up with the editor version it would make sense to keep them in sync in this case. Would also be an appropriate time to move to npm instead of bower for the editor, (since that's the general direction for ember-cli anyway).
