### ISSUE TITLE
initialized / initializationDelayed callbacks are not fired

### ISSUE THREAD

**Issue by mani-rsg** [froala/ember-froala-editor#120]
Hi Team,

The `initialized` and the `initializationDelayed` (when `initOnClick` option is set to `true`) event callbacks are not getting fired after froala successfully initialized. 

When debugged, found that the `typeof` operator is missed in  `frontend/node_modules/ember-froala-editor/addon/components/froala-editor.js` line 269.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/72298612/181011727-6cfe0c11-3944-4a64-81ac-b59d3b50060d.png">

**Comment by Panman82** [comment]
Should mention, I would expect a release in the next couple of weeks.
