### ISSUE TITLE
Image Plugin

### ISSUE THREAD

**Issue by TomWsl** [froala/ember-froala-editor#122]
Does [ember-froala-editor](https://github.com/froala/ember-froala-editor) support Froala editor image plugin?

**Comment by Panman82** [comment]
While I haven't used it personally, and don't know the best configuration options for the plugin, the Ember addon can certainly import the plugin for you. You'll probably need to change the [upload URL options](https://froala.com/wysiwyg-editor/docs/options/#image) and such to ensure images go to the correct place.

```js
// ember-cli-build.js
// ... (snip)
let app = new EmberApp(defaults, {
  'ember-froala-editor': {
    plugins: ['image']
  }
});
// ... (snip)
```

**Comment by Panman82** [comment]
Hi @TomWsl, I'm going to close this for now but if you still need help comment here and I'll open it up again.
