### ISSUE TITLE
Ember 2.8 Support

### ISSUE THREAD

**Issue by mwadden** [froala/ember-froala-editor#13]
Hi,

Is there an ETA on when the latest couple of commits (for Ember 2.8 support) will be bundled into a new release? We're in the process of upgrading our app to 2.8 and now froala is throwing all kinds of errors which are blocking our efforts.

Thanks!

**Comment by Panman8201** [comment]
The froala folks have released new versions of this addon along side froala-editor releases (which can make situations like these difficult). What I could do is release a beta if that'll help you.

**Comment by mwadden** [comment]
Thanks for the quick response. That'd be great if it's not too much trouble. Worst-case scenario, we can either fork the project or just apply the patches locally until the release comes.

Thanks for your help.

**Comment by mike183** [comment]
You could always lock the add-on version in your `package.json` file to a specific commit SHA.

E.g. the following will install the add-on including the Ember 2.8 compatibility commits:

```
"ember-froala-editor": "https://github.com/froala/ember-froala-editor#28eeee2f646dd3150149f9372dd990c1a672570b"
```

**Comment by mwadden** [comment]
Really? That's awesome... I didn't know that was possible. Thanks @mike183, I'll give that a shot.

**Comment by mwadden** [comment]
Worked perfectly. Thx again.
