### ISSUE TITLE
Enable Travis CI integration for testing

### ISSUE THREAD

**Issue by Panman8201** [froala/ember-froala-editor#23]
Also add the badge to the README. [Should just be a matter of](http://emberup.co/ember-addon-secrets/#continuousintegrationdomination) getting the [GitHub integration](https://github.com/integrations/travis-ci) setup...

CC: @stefanneculai I would need access to the repo Settings, unless you're able to get it setup for us. Thanks

**Comment by Panman8201** [comment]
Ping @stefanneculai Just want to check in on this case. Any chance you can look into Travis CI integration for us?

**Comment by Panman8201** [comment]
Pinging @stefanneculai Hoping you have some time now that 2.4 is out and we're winding down to the holidays. I really think this is just a matter of you going in and clicking a button to add Travis CI integration (I have the config file ready to go in the repo). Please let me know what your thoughts are here. Thanks!

**Comment by stefanneculai** [comment]
Done.
