### ISSUE TITLE
No content rendered

### ISSUE THREAD

**Issue by Blackening999** [froala/ember-froala-editor#25]
Hello!

Awesome editor!

I found one issue. When user opens the editor with already existing content passed by property in .hbs (content=userContent) - editor do not show it. From code I've investigated it occur due to the fact editor updating content only when property '_editorInitializing' is set to true, which isn't working for init load.

Please, advise

**Comment by Panman8201** [comment]
Are you using the [latest beta](https://github.com/froala/ember-froala-editor/releases) of this addon? It works around a couple issues with recent froala editor releases. Also, what is your full usage of the editor component? Ex: `{{froala-editor content=userContent}}`

The way it works now is that the `content` is rendered [once in the component template](https://github.com/froala/ember-froala-editor/blob/master/addon/templates/components/froala-editor.hbs#L3), which the froala editor picks up [when initialized](https://github.com/froala/ember-froala-editor/blob/master/addon/components/froala-editor.js#L232).

**Comment by Panman8201** [comment]
@Blackening999 do you need any further help here?

**Comment by Blackening999** [comment]
@Panman8201 We'll try new beta and if it's fine I won't give any feedback here in the next 2 weeks ;)

**Comment by Panman8201** [comment]
Closing. Feel free to report back if you do run into issues. The latest version, 2.4, has been release.
