### ISSUE TITLE
Installing tries to install ember-cli-font-awesome which breaks

### ISSUE THREAD

**Issue by bfeltman** [froala/ember-froala-editor#26]
When I try to install this it tries adds ember-cli-font-awesome to my package.json file, when then breaks.  Shouldn't it just be using ember-font-awesome instead?  How can I install this without the ember-cli-font-awesome?

Thanks,

**Comment by Panman8201** [comment]
Yes, sorry, not sure how that was missed. Although I would have expected the install to still work, `ember-font-awesome` was renamed _from_ `ember-cli-font-awesome` before version 2 of that addon.
