### ISSUE TITLE
Hide on-blur with binding

### ISSUE THREAD

**Issue by niksa88** [froala/ember-froala-editor#30]
Hide on-blur with binding does not working on Ember 2.9.0 and below

`{{froala-editor  content=myValue
                 update=(action (mut myValue))
                 options=(hash initOnClick=true)
                 on-blur=(froala-method "reinit")}}`

**Comment by Panman8201** [comment]
Yeah, there seems to be something weird going on with that one. Not sure what's going on just yet. From the testing I've done so far, it's definitely something with ember-land, like the click event doesn't make it to the editor initially.

FYI, same as #27
