### ISSUE TITLE
Build failing after 2.6.0 update

### ISSUE THREAD

**Issue by Panman8201** [froala/ember-froala-editor#32]
Need to review. https://travis-ci.org/froala/ember-froala-editor/jobs/228693041

**Comment by Panman8201** [comment]
Haven't had a good chunk of time to really dig in, but every time a test fails it's referring to `b.$tb.find` and `$tb` is undefined/null.

**Comment by Panman8201** [comment]
I think this is related to froala/wysiwyg-editor#1978, to be fixed in the 2.6.1 release. Will test once available.

**Comment by stefanneculai** [comment]
2.6.1 has just been released. @Panman8201 do you think it would work now?

**Comment by Panman8201** [comment]
Yep, fixed by a44833464729296ff39ecc180e5ed158f9281361

**Comment by Panman8201** [comment]
@stefanneculai yep, seems to be ok now. I'll work on releasing today.

**Comment by stefanneculai** [comment]
Thanks a million!
