### ISSUE TITLE
Drag / Resize Options?

### ISSUE THREAD

**Issue by dephora** [froala/ember-froala-editor#33]
Curious if anyone doing anything specific to make the editor draggable / resizeable or is the best option to create a wrapper div and handle everything in there and have froala resize based on that. I'm currently doing that with Summernote but the resize in particular isn't elegant.

Thanks for the addon.

**Comment by Panman8201** [comment]
Unsure about that option. Might be worth posting over in the repo for the actual editor too: https://github.com/froala/wysiwyg-editor

**Comment by dephora** [comment]
Yeah, resizing 'is in the pipeline' from last March but no ETA. Dragging can be handled easily enough outside of it.

**Comment by Panman8201** [comment]
I'm going to close this for now. If you have specific questions for this addon feel free to open another issue. Thx
