### ISSUE TITLE
Sass problems

### ISSUE THREAD

**Issue by ndemonner** [froala/ember-froala-editor#37]
Styles don't seem to be getting added correctly into the asset tree when used alongside ember-cli-sass. Am I missing something easy here? Let me know what would be helpful to see to assist debugging.

**Comment by Panman8201** [comment]
Humm... `froala-editor` does not provide `*.sass` files... But I believe `ember-cli` should be pulling in the proper `*.css` files when your project builds, regardless. Is this not what you are seeing?

**Comment by ndemonner** [comment]
I thought so, too, but apparently not. It looks like there's a little prep that needs to be done so that we can use `@import "ember-froala-editor"` to pull in the necessary files. https://github.com/aexmachina/ember-cli-sass#addon-usage has some details.

For now, I've manually pulled in the CSS (including theme file), and used ember-font-awesome to get the icon fonts to work.

**Comment by Panman8201** [comment]
> It looks like there's a little prep that needs to be done so that we can use @import "ember-froala-editor" to pull in the necessary files. https://github.com/aexmachina/ember-cli-sass#addon-usage has some details.

That's if the addon want's to use `ember-cli-sass` itself, so if `froala-editor` *did* provide Sass files... But this addon already calls that particular code anyway. https://github.com/froala/ember-froala-editor/blob/v2.6.1/index.js#L63

I'll have to try a quick dummy project using both addons to troubleshoot. Probably confirm on Slack what the expected output would be too.

**Comment by ndemonner** [comment]
Yeah, that was my initial reading of it too, but it's not working for me unless I have some way of directly `@import`ing stuff. I appreciate you taking the time out to check on it—if others have used ember-cli-sass with this addon successfully, then it's probably something on my end.

**Comment by Panman8201** [comment]
So I just did a quick test and all seemed well. Here is what I did;

1. `ember new froala-sass`
2. `cd froala-sass`
3. `ember install ember-cli-sass`
4. `ember install ember-froala-editor`
5. Renamed `app/styles/app.css` to `app.scss`
6. Added `body * { color:red }` to the `app.scss` file just to make sure that was working
7. Added `{{froala-editor}}` to `app/templates/application.hbs`
8. `ember server`
9. Visited `http://localhost:4200` in Chrome

All appeared well, the text was red and the editor showed up with styling and font awesome icons. Not sure how to debug your project from here though... Must be something with sass configuration. What does your `sassOptions` look like?

**Comment by ndemonner** [comment]
Hmm, the plot thickens. Anywho, here's what's in my `ember-cli-build.js`:
```
    sourcemaps: {
      enabled: true
    },
    autoprefixer: {
      browsers: ['last 2 versions']
    },
    babel: {
      plugins: [
        'babel-plugin-transform-object-rest-spread'
      ]
    },
    'ember-froala-editor': {
      plugins: [
        'align',
        'char_counter',
        'fullscreen',
        'help',
        'line_breaker',
        'link',
        'lists',
        'quote',
        'url',
        'word_paste',
        'file',
        'image',
        'special_characters'
      ],
      languages: false,
      themes: false
    },
    'ember-font-awesome': {
      useScss: true
    }
```

Nothing else... but seems like it has nothing to do with this addon, so I'll investigate further on our end. Feel free to close, and if I run into something that will help others, I'll post it here later.

**Comment by Panman8201** [comment]
So I tried all of that config (except the babel plugin) and everything still seems to work ok. Perhaps it's other addons or version differences. What does your `package.json` `dependencies` and `devDependencies` look like? After that, I'm not really sure..

**Comment by ndemonner** [comment]
```
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-auto-focus": "^1.0.8",
    "ember-awesome-macros": "^0.36.0",
    "ember-changeset": "^1.2.3",
    "ember-changeset-validations": "^1.2.6",
    "ember-cli": "^2.13.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-autoprefixer": "^0.7.0",
    "ember-cli-babel": "^6.1.0",
    "ember-cli-clipboard": "^0.5.0",
    "ember-cli-dependency-checker": "^1.4.0",
    "ember-cli-eslint": "^3.1.0",
    "ember-cli-htmlbars": "^1.3.2",
    "ember-cli-htmlbars-inline-precompile": "^0.4.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-moment-shim": "^3.1.0",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-rails-addon": "^0.8.0",
    "ember-cli-sass": "^6.1.3",
    "ember-cli-sentry": "^2.4.3",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-click-outside": "^0.1.9",
    "ember-concurrency": "^0.8.3",
    "ember-data": "^2.13.1",
    "ember-date-components": "^1.0.0",
    "ember-export-application-global": "^2.0.0",
    "ember-font-awesome": "^3.0.5",
    "ember-form-for": "^2.0.0-alpha.15",
    "ember-froala-editor": "^2.6.1",
    "ember-highcharts": "^0.5.4",
    "ember-keyboard": "^2.1.10",
    "ember-load-initializers": "^1.0.0",
    "ember-macro-helpers": "^0.14.0",
    "ember-message-bus": "^0.3.3",
    "ember-moment": "^7.3.0",
    "ember-power-select": "^1.8.3",
    "ember-power-select-typeahead": "^0.5.8",
    "ember-power-select-with-create": "^0.4.3",
    "ember-query-params-reset": "^2.0.0",
    "ember-resolver": "^4.0.0",
    "ember-router-service": "^1.0.2",
    "ember-sortable": "^1.9.3",
    "ember-source": "^2.13.0",
    "ember-string-helpers": "^1.0.2",
    "ember-tether": "^1.0.0-beta.0",
    "ember-tooltips": "^2.9.0-beta.0",
    "ember-validators": "^1.0.1",
    "ember-webcam": "^0.0.4",
    "ember-welcome-page": "^3.0.0",
    "highcharts": "^5.0.11",
    "ivy-tabs": "^3.1.0",
    "loader.js": "^4.4.0"
  },
  "engines": {
    "node": ">= 4"
  },
  "private": true,
  "dependencies": {
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "ember-ds-inline-edit": "^0.3.1",
    "ember-simple-auth": "^1.3.0",
    "ember-truth-helpers": "^1.3.0",
    "mapbox-gl": "^0.37.0",
    "minimatch": "^3.0.4"
  }
```

The only thing in there I can think of that might affect CSS load order stuff would be autoprefixer.

**Comment by Panman8201** [comment]
Sorry, I haven't had a chance to test all of your dependencies. Nothing stands out as potential problems, but I don't know the ins-and-outs of all of those.

**Comment by ndemonner** [comment]
I'll close this for now, and when I have time to figure it out (and if I figure it out) I'll comment for the benefit of others. Thanks for looking into it.

**Comment by robclancy** [comment]
I had either removed `<link integrity="" rel="stylesheet" href="{{rootURL}}assets/vendor.css">` or it wasn't a thing when we started our project years ago which was the reason I never had styles coming up. Just incase that is your issue.
