### ISSUE TITLE
Browse files from server froala

### ISSUE THREAD

**Issue by krnbatta** [froala/ember-froala-editor#38]
I want to browse files from my server. But, by default, images are being served from froala server.
![image](https://user-images.githubusercontent.com/8068341/26957944-a43e0d68-4ce5-11e7-9474-1472181f830e.png)

**Comment by stefanneculai** [comment]
Please follow the guides from our website for that: https://www.froala.com/wysiwyg-editor/docs/concepts/image/manager.
