### ISSUE TITLE
Extending the editor does not render

### ISSUE THREAD

**Issue by lvegerano** [froala/ember-froala-editor#41]
Trying to extend the component causes it to not render. [Here](https://ember-twiddle.com/a2f9f35b310a5931224e2529e732e65b?openFiles=templates.components.froala-extended.hbs%2C) is an example. 

While `$element.froalaEditor( this.get('_options') );` run it just doesn't do anything.

**Comment by filipecrosk** [comment]
You just need to remove the component's template: `app/templates/components/froala-extended.hbs`.

I tried it on your twiddle link and worked. :)

**Comment by Panman8201** [comment]
Yeah, what @filipecrosk said about the template, I'll add a note about that in the docs. Did that work for you?

**Comment by lvegerano** [comment]
@filipecrosk @Panman8201 yes thank you very much for the help!
