### ISSUE TITLE
Event handling breaks when deleting one of multiple froala editors.

### ISSUE THREAD

**Issue by natashad** [froala/ember-froala-editor#43]
### Description:
Create multiple instances of the froala-editor open up the first one and upload an image. Then delete the first editor. Try adding an image in the second editor, the popup disappears and the file explorer never opens.
http://recordit.co/veHZJUx4YC

### Code Example: 

  ```
{{#if showFroala}}
  {{froala-editor options=exampleOptions toolbarInline=true}}
{{/if}}

<button {{action (mut showFroala) false}}>DELETE ONE</button>

{{froala-editor options=exampleOptions toolbarInline=true}}
```

### Notes
What seems to be going on is that when deleting the first section, the destroy method gets called that deletes all the event handlers. ( in froala_editor.js --> FE.prototype.destroy )

**Comment by Panman8201** [comment]
I can't seem to replicate the issue. Event handlers are attached directly to the editor, so they shouldn't be removed from each other (when destroyed). Can you provide more details?

**Comment by natashad** [comment]
Steps to reproduce:
* clone: https://github.com/natashad/ember-froala-editor
* git checkout natashad-patch-1
* run `ember server`
* In Chrome - navigate to localhost:4200
* Upload an image into the first editor.
* Click on the "DELETE ONE" button to delete the first editor.
* Click on Insert Image in the second editor.
* Click "Drop Image"

### EXPECTED ###
* The file browser appears
* Selecting a file successfully uploads image.

### ACTUAL ###
* Clicking on "Drop Image" makes the pop up disappear and nothing else happens on the page.

![vehzjux4yc](https://user-images.githubusercontent.com/1857154/28330149-85789260-6bba-11e7-9469-32281a622f24.gif)

**Comment by Panman8201** [comment]
Alright, I was able to replicate your issue specifically, but I don't think it's with eventing in "ember land". If I attach image events they still fire, or drag-n-drop still works either way. It seems to be some bug with the froala-editor specifically, but I'm not sure exactly how. I removed the Ember component of this issue by [replicating it in JS Fiddle](https://jsfiddle.net/Panman8201/z5ux2c32/). Can you start an Issue over on the [froala editor repo](https://github.com/froala/wysiwyg-editor/issues)?

**Comment by natashad** [comment]
Thanks @Panman8201! I'll close this and open the issue there.
