### ISSUE TITLE
gh-pages Website Broken (Docs)

### ISSUE THREAD

**Issue by Panman8201** [froala/ember-froala-editor#44]
It seems like the gh-pages Website is now redirecting to a custom domain. I'm unsure if this is intended... Originally it used the typical GitHub subdomain: http://froala.github.io/ember-froala-editor/ Now it's trying to go to http://www.emberwysiwygeditor.com/, which breaks the asset links and ember router.

@stefanneculai can you confirm if this is intended? I'm guessing it was changed in the repo Settings.

**Comment by stefanneculai** [comment]
Yes, this is intended. We started to make this change.

**Comment by Panman8201** [comment]
Alright, I'll change the docs code for this domain and update appropriate links.

Just want to throw this out there, I'm not sure what the Ember community will think about this domain. Since Froala isn't in the name, it lends to assuming it's the "official" Ember editor.

**Comment by stefanneculai** [comment]
We haven't thought of it this way, however, I believe it is quite obvious from the logo and text from the page that it's not the case. Our intention was just to make it easier to find by the Ember devs.

**Comment by Panman8201** [comment]
Sure, should be clear once you get there. The most common approach other addons take is to get a domain with the same name as the addon. In this case either ember-froala-editor.com or emberfroalaeditor.com. Just putting in my 2 cents.

**Comment by Panman8201** [comment]
Oh, also wanted to mention that the workflow for ember devs to find addons is to use either; https://www.emberobserver.com/ or https://www.emberaddons.com/. This addon can be found on both so "findability" should be alright. Just wanted to point that out, in case you aren't familiar with the ember ecosystem. :)

Working on the docs now..

**Comment by Panman8201** [comment]
@stefanneculai reopening because the editor on the docs site is now showing "Unlicensed". I assume you'll need to re-issue a key found [here](https://github.com/froala/ember-froala-editor/blob/v2.6.4/tests/dummy/app/components/froala-editor.js#L5)?

**Comment by stefanneculai** [comment]
This one should be the one to use: 'Tvywseoh1irkdyzdhvlvC8ehe=='.

**Comment by Panman8201** [comment]
Great, fixed! Published docs update w/ new key.
