### ISSUE TITLE
Backspace throws error

### ISSUE THREAD

**Issue by mukk85** [froala/ember-froala-editor#46]
When deploying to production, I get the following error when pressing backspace. This causes none of the text to save. 

**Uncaught SyntaxError: Invalid regular expression: /([�-􏰀-�‍]+)$/: Range out of order in character class
    at new RegExp (<anonymous>)**

This just started in 2.6.6

**Comment by stefanneculai** [comment]
What HTML do you have in the editor when using backspace?

**Comment by Panman8201** [comment]
Humm... do you have a stack trace showing the origination of the error? Perhaps it's related to https://github.com/froala/ember-froala-editor/commit/f83ca05c3133b1db159465858ca3f3a03ee4744e although I'm not sure why that would be occurring only on backspace...

**Comment by Panman8201** [comment]
Another thought, does it still happen if you go back to 2.6.5 of this addon? (Which should still install 2.6.6 of the froala-editor.) That would also narrow it down to addon vs editor.

**Comment by mukk85** [comment]
It is the editor that is the problem, or perhaps the way ember-cli minifies the code. If I revert back to 2.6.5 of the editor it doesnt have the error. If I use 2.6.5 of this plugin with 2.6.6 editor the error remains.

**Comment by mukk85** [comment]
It is in FE.MODULES.cursor, and is this RegExp: c=new RegExp("([\ud83c-\udbff\udc00-\udfff\u200d]+)"+(b?"":"$"),"i"). In chrome it is converted to those broken unicode symbols. I noticed in 2.6.5 the first slash is escaped in each of the strings (along with having a different regex).

**Comment by Panman8201** [comment]
It does look correct in the `froala-editor` package installed from npm. So you are probably right in that it's ember-cli re-minifying that file and messing it up. I'm checking to see if I can exclude that from minification in ember-cli. Perhaps @stefanneculai can change something too, but I think the root issue is within ember-cli.

**Comment by stefanneculai** [comment]
@mukk85 @Panman8201 it looks like there was a RegExp unicode which wasn't escaped correctly. I've just updated it and we'll include it in release 2.6.7.

**Comment by stefanneculai** [comment]
We just published the new version 2.7.0.
