### ISSUE TITLE
Test helper 'fillInFroalaEditor' not working

### ISSUE THREAD

**Issue by raphaelns-developer** [froala/ember-froala-editor#49]
I'm tring to use the helper `fillInFroalaEditor` in my acceptance test but isn't working correctly. The helper fill in the froala instance with the text that i have passed, but the `content` property is not updated with the text unless i force the test to click in something else like a button to take the focus off the froala editor.

**Comment by Panman8201** [comment]
Can you provide a snippet of code which you are trying to accomplish? The helper uses a Froala function to set the content, so I'm surprised the editor wouldn't pick up that change immediately.

**Comment by pwilms** [comment]
yea, we can see the same issue

```
visit("/page/" + category.id);
    andThen(function () {
      fillInFroalaEditor('#page .froala-editor-container', '<p>asdasd</p>');
      andThen(() => {
         assert.equal(find(`.details .title}')`).text().trim(), `${title} *`);
    });
```

When the content property is updated we append a * to a tab and the assertion above checks if it's appended. So the content property is not updated with the fillIn helper. 

even with a simple test it doesnt update 

in template the follwing above the editor:
`<div id="foo">{{model.content}}</div>`

```
fillInFroalaEditor('#knb-entry-custom-information-form .froala-editor-container', '<p>asdasd</p>');
      andThen(function () {
        assert.equal(find('#foo').text().trim(), "asdasd");
      });
````
![Alt text](https://i.imgur.com/Vn3VDbp.png)

**Comment by Panman8201** [comment]
Ah, so you are expecting the `update` event to fire too (not _just_ checking the DOM). I'm thinking it gets back to the fact that [`html.set` does not trigger the `contentChanged` event](https://github.com/froala/wysiwyg-editor/issues/1578). I just pushed a change that will force the event to fire, triggering your typical `update` event.

**Comment by pwilms** [comment]
works perfectly for me :) i hope for @raphaelns-developer  too

**Comment by Panman8201** [comment]
Great! I have a few other things to update here and then I'll publish a new version.

**Comment by raphaelns-developer** [comment]
Great! I think this is the solution, but i will test it tomorrow

**Comment by raphaelns-developer** [comment]
Hey @Panman8201. After some time i have another question for you using the same helper: it is possible to use the `fillInFroalaEditor` in integration tests?

**Comment by Panman8201** [comment]
@raphaelns-developer Sorry for the delay, but I'm just unsure and tried to do some research but came up empty. Have you tried using it? If anything, I wonder if the import process would be different for acceptance vs integration.

**Comment by raphaelns-developer** [comment]
@Panman8201 Yes, i already tried, but in the helper you use the `find` helper and i know no why it only works in acceptance tests. Maybe if you change the `find` to JQuery it will work in any test.

**Comment by Panman8201** [comment]
Closing this as [Version 2.7.5](https://github.com/froala/ember-froala-editor/releases/tag/v2.7.5) includes this fix.

@raphaelns-developer if you want to continue exploring the helper in integration tests let's open another issue.
