### ISSUE TITLE
Allow Importing third_party Plugins

### ISSUE THREAD

**Issue by anlumo** [froala/ember-froala-editor#50]
froala-editor is shipped with three third party plugins: embedly, image_aviary and spell_checker. However, ember-froala-editor doesn't allow importing them from the configuration in ember-cli-build.js, since they're in their own directory called third_party and not in plugins.

Reading through the importing code, I also don't see a way to outsmart the importer (I already tried `../third_party/embedly` without success).

**Comment by Panman8201** [comment]
Interesting, that must be fairly new, hadn't noticed those before. It'll be a bit tricky to determine enable the ability to pull plugins from another folder too, but I'll take a look.

**Comment by stefanneculai** [comment]
@Panman8201 indeed, this is something new we added for plugins which wrap around 3rd party tools. We did that in order to make it clear that those plugins are using 3rd party services.

**Comment by Panman8201** [comment]
FYI, I've been trying to find some time to look at this. If I don't get to it soon, it'll be done before the new year (when I have a week off from work).

**Comment by Panman8201** [comment]
FYI, still on my radar. Been working on updating the upstream `ember-cli-bootswatch` (unpublished commits yet) to move away from bower. Then I'll be working on a bunch of stuff here.

**Comment by anlumo** [comment]
Thank you!

**Comment by Panman8201** [comment]
Released 2.7.6-beta.1 with support for `third_party` plugins. Just to note, including those seemed to be causing test errors for the addon, so I'm not sure what's going on there (maybe plugin bugs.?.).
