### ISSUE TITLE
ember-froala-editor is using their version of JQuery (1.7.2) or Ember default JQuery 3.2.1 ?

### ISSUE THREAD

**Issue by anandi2i** [froala/ember-froala-editor#51]

**Comment by Panman8201** [comment]
This addon does _not_ import jQuery from the froala-editor dep because it should be using whatever ember brings in. On the [documentation site](http://www.emberwysiwygeditor.com/), jQuery 3.2.1 is being used.

**Comment by Panman8201** [comment]
@anandi2i does that answer your question or concern?

**Comment by stefanneculai** [comment]
@anandi2i @Panman8201 the `ember-froala-editor` is using whatever jQuery version is there in the project. If you don't have any jQuery, then the `froala-editor` package would import a version higher than 1.11.0.

**Comment by Panman8201** [comment]
@anandi2i let us know if you have further questions. Can re-open the ticket but closing for now.

**Comment by anandi2i** [comment]
@Panman8201 Thanks for the answer...and will raise if anything needed..
