### ISSUE TITLE
error when after upload image in custom server

### ISSUE THREAD

**Issue by cahyowhy** [froala/ember-froala-editor#53]
i am trying to upload image to my server. Image was uploaded successfully
![screenshot from 2018-01-23 13-14-49](https://user-images.githubusercontent.com/18083469/35260722-87f91ae0-003f-11e8-83d9-bca994d31ad1.png)

but i get an error
![screenshot from 2018-01-23 13-13-32](https://user-images.githubusercontent.com/18083469/35260752-ae517a8e-003f-11e8-93f9-4240a6b21838.png)

btw this is my froala options
```
let options = {
      heightMin: 400,
      imageUploadParam: 'file[]',
      imageUploadParams: {image: new Image().toString()},
      imageUploadURL: `${ENV.IMAGE_API}/upload`,
    };

    if (!_.isEmpty(user)) {
      options = Object.assign(options, {
        requestHeaders: {
          Authorization: user['token']
        }
      });
    }
```

can anyone solve this.. sorry for my bad english :(

**Comment by stefanneculai** [comment]
@cahyowhy it looks like there is a problem on how the image is stored on server side. For tech support please reach us via our website: https://www.froala.com/wysiwyg-editor/contact.
