### ISSUE TITLE
Using the `fillInFroalaEditor` test helper within integration tests

### ISSUE THREAD

**Issue by Panman8201** [froala/ember-froala-editor#55]
@raphaelns-developer I went through the latest testing stuff and made a few changes to the exported `fillInFroalaEditor()` test helper. Can you update to the latest beta and try the following in your integration tests?

```js
import { fillInFroalaEditor } from 'ember-froala-editor/test-support';

// ... from within a test...
await fillInFroalaEditor('#selector', '<p>New HTML to "fill in".</p>');
```

**Comment by raphaelns-developer** [comment]
@Panman8201 Sorry for the delay, but the helper is working just fine. Thanks
