### ISSUE TITLE
licensing and local development

### ISSUE THREAD

**Issue by jakemoves** [froala/ember-froala-editor#6]
Hey, I couldn't find an answer for this on the Froala site.

I'm using this Ember addon. I purchased a license but can't find any documentation on whether the single-domain license includes localhost. Can you please advise?

**Comment by stefanneculai** [comment]
The One Domain license allows you to generate a single license key for single domain. However, you can use the editor without any restrictions on your development and tests domains. You might see an unlicensed message at the bottom of the editor, but that won't limit any of the editor's features.

**Comment by jakemoves** [comment]
Thanks so much Stefan!
