### ISSUE TITLE
Inserting into Froala editor the Ember way?

### ISSUE THREAD

**Issue by parsurv** [froala/ember-froala-editor#64]
Hi Guys,

This is more of a how-to? in terms of best practice rather than a question.

We have a requirement to insert html from a parent component wrapping the Froala editor. 
This is based on the user clicking on something like a insert button out side of the editor. 
The solution that we have gone with as of now is as follows. 
- We have extended the core froala editor and have an attribute called editor input.
- Whenever we want to insert we would set the editorInput from the parent and then in the didUpdateAttrs hook the content html would be inserted into the editor.

A sample of the code snippet is shown below. 
```
import FroalaEditorComponent from 'ember-froala-editor/components/froala-editor';
export default FroalaEditorComponent.extend({
    editorInput: null,
    didUpdateAttrs() {
       this._super(...arguments);
       // Hack implementation
       if (Ember.isPresent(editorInput)) {
          this._insertHTML(editorInput);
         Ember.run(() => {
            set(this, 'editorInput', null);
         });
       }
    },
    _insertHTML(editorInput) {
        ...
    }
});
```
----------------------------------------------------------------------------------------
This seems to be breaking lots of ember conventions and in some sense is more of a hack.
The other options that we can think of are:
1. Create event based hook onto the editor via ember evented.
2. Create promise based actions from within the Froala editor that will be resolved from the parent. Not sure if this is feasible!
3. Pass the context of the child to the parent and call the Froala apis from above. This seems to be a hack again.  

I wanted to get some advice from you folks to see if there is any best practices on how html insert can be done that is spanning multiple components. Would really appreciate it!!!

**Comment by Panman8201** [comment]
Humm... if I'm understanding right, I think what you'll want to do is have the parent component capture the editor `on-initialized` and then fire the [insert method](https://www.froala.com/wysiwyg-editor/docs/methods#html.insert) as needed. Ex:

```hbs
{{#parent-wrapper}}
  {{froala-editor content (action (mut content)) on-initialized=(action "registerEditor")}}
  <button {{action "insertContent"}}>Insert Content</button>
{{/parent-wrapper}}
```

```js
// parent-wrapper.js
import Ember from 'ember';
export default Ember.Component.extend({

  content: '<p>Initial Content</p>',
  insertContent: '<p>Inserted Content</p>',

  actions: {
    registerEditor(component) {
      this.set('froalaEditor', component);
    },
    insertContent() {
      this.get('froalaEditor').method('html.insert', this.get('insertContent'));
    }
  }

});
```

**Comment by parsurv** [comment]
@Panman8201 
We have currently changed our implementation to pass the scope of the child Froala itself and then call the necessary methods as action APIs. I was under the impression that this way may cause some unforeseen issues later on. 

Happy to know that you are suggesting something similar 👍 

Thank you very much!

**Comment by Panman8201** [comment]
Great, feel free to comment here again if you have further questions!
