### ISSUE TITLE
deprecation message spammed when including ember-froala-editor in engines

### ISSUE THREAD

**Issue by robclancy** [froala/ember-froala-editor#65]
> DEPRECATION: ember-froala-editor: The default value for the 'plugins' option has change from 'true' to 'false'. Please update 'ember-froala-editor.plugins' in 'ember-cli-build.js' to indicate which plugin(s) you need; string = one plugin name, array = multiple plugin names, true = all plugins, false = no plugins.

This is spammed (even though set in `ember-cli-build.js`) when ember engines get access. I'm not sure if this means that there is a bug with showing the message where it should just not show at all in engines or if engines aren't getting the correctly configured package.

**Comment by Panman8201** [comment]
Interesting, I haven't used engines at this point so I'll have to investigate. Are you using an in-repo engine or "addon" engine?

**Comment by robclancy** [comment]
in-repo engines.

**Comment by Panman8201** [comment]
Finally looking into this. Couple questions;

1. Is the ember-froala-editor dependancy located in `/package.json` or `/lib/engine-name/package.json`?
2. Is the ember-froala-editor config located in `/ember-cli-build.js` or `/lib/engine-name/index.js`?

**Comment by robclancy** [comment]
1. it's in `/package.json` and then any engine that also uses it will have it in its `package.json` as well with version set to `*`, which basically just has ember link back to the applications version.
2. the config is only in the `/ember-cli-build`

**Comment by jrjohnson** [comment]
This happens when `ember-froala`editor` is in the `dependencies` section of an addon as well. 

Even with configuration in the consuming apps `ember-cli-build.js` the message still shows up. 

This is probably because of https://github.com/froala/ember-froala-editor/blob/master/index.js#L57

many addons use a pattern like
https://github.com/FortAwesome/ember-fontawesome/blob/master/index.js#L158-L165 

to get to the host app, I have no idea how correct this is, I've just been copying it.  There is also a private method called `_findHost` that I've seen used to do the same thing.

**Comment by Panman8201** [comment]
@jrjohnson yeah, I remember having to do some funny stuff like that before. I'm checking on Discord if that's the best solution or if there is something better. Thx for the point in the (probably) right direction.

**Comment by Panman8201** [comment]
Alright, I believe this should be fixed with https://github.com/froala/ember-froala-editor/commit/9ae40c65d4edfba4b943112cad81bd4f5ee921bb and https://github.com/froala/ember-froala-editor/commit/658946e5118fa51ed99fab9255e1326f3c457ec1. Anyone here able to test this from master?

**Comment by robclancy** [comment]
@Panman8201 works

**Comment by Panman8201** [comment]
@robclancy great! Closing for now but can re-open if anyone continues to run into this issue. FYI, it will be in the next release, v2.8.6 (whenever Froala has their next release).

**Comment by jrjohnson** [comment]
@Panman8201 any chance of a `2.8.5-1` release with this fix? In addition to the warning output this issue also means it's not possible to configure froala in an addon. It doesn't look like froala is on a fixed schedule and I'm worried about waiting a few more months for this fix.

**Comment by Panman8201** [comment]
I've been in contact with Froala and they have a release coming next week. However, I'll work on a +1 release today since several are waiting on this fix.

**Comment by Panman8201** [comment]
FYI, I tried to publish as 2.8.5+1 but NPM didn't like that. 2.8.5-1 would technically be a pre-release and fall lower than the current 2.8.5 in priority, so it wouldn't get installed. I need to determine what our best approach is here. I was considering +1, +2, +3... but it seems NPM won't like that. Release everything as -1, -2, -3.?. (sigh)

**Comment by jrjohnson** [comment]
Damn! Sorry about that. If there is a release next week anyway then I can easily just be patient and run off of `master` for a bit. I was just concerned when I looked at the release history and saw some multi-month gaps. Sorry I wasted some of your time on this, thanks for taking a look.

**Comment by robclancy** [comment]
The people making these decisions are froala are just stupid. @jrjohnson just use the commit directly for now. Here is what I have been using since this was patched. `"ember-froala-editor": "froala/ember-froala-editor#658946e5118fa51ed99fab9255e1326f3c457ec1",`

**Comment by Panman8201** [comment]
FYI, I've just publish v2.9.0
