### ISSUE TITLE
Do ember-froala-editor support @mention ?

### ISSUE THREAD

**Issue by Koushikrad** [froala/ember-froala-editor#67]
General froala editor support @mention user name as explained in below link

https://www.froala.com/wysiwyg-editor/examples/at-js

Do ember-froala-editor support the same?

**Comment by Panman8201** [comment]
You would have to bring in At.js separately from this addon. Maybe the [ember-cli-at-js](https://www.emberobserver.com/addons/ember-cli-at-js) addon, but it hasn't been updated in two years... Otherwise follow the typical way to add a third party lib and `import` the proper assets.

Then the usage with this addon could be handled with `action` event handlers on the `{{froala-editor}}`.

```
{{froala-editor on-initialized=(action "loadAtJs") on-keydown=(action "handleAtJsKeydown")}}
```

Then on the controller or parent component;

```
import Controller from '@ember/controller';
import $ from 'jquery';

export default Controller.extend({

  actions: {

    loadAtJs( component ) {
      let editor = component.get('editor');
      let config = {}; // Build the At.js config
      editor.$el.atwho(config);
    },

    handleAtJsKeydown( component, event ) {
      let editor = component.get('editor');
      if (event.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
        return false;
      }
    }

  }

});
```

To do this for *all* instances of the `{{froala-editor}}`, you can override the component in your app and add the handlers there.

```
// app/components/froala-editor.js
import FroalaEditorComponent from 'ember-froala-editor/components/froala-editor';

export default FroalaEditorComponent.extend({

  'on-initialized' : function( component ) {
    let editor = component.get('editor');
    let config = {}; // Build the At.js config
    editor.$el.atwho(config);
  },

  'on-keydown': function( component, event ) {
    let editor = component.get('editor');
    if (event.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
      return false;
    }
  }

});
```

**Comment by koushik-radhakrishan** [comment]
@Panman8201 thanks for replying. I tried the same and it works well :) thank you so much

**Comment by Panman8201** [comment]
Sounds good. Closing for now but can certainly re-open if further discussion is needed.

**Comment by avillarubia** [comment]
Good day guys,

I know this is a very long time ago discussion, I wonder how does this looks because I am looking for something that I can mention a person inside the editor. Do you mind giving me a screenshot @koushik-radhakrishan ?

**Comment by koushik-radhakrishan** [comment]
@avillarubia [check this link](https://froala.com/wysiwyg-editor/v2-0/examples/at-js/) it looks similar to this. You can try it in ember as @Panman82 said in the above comment :) I further suggest you use [tribute](https://github.com/zurb/tribute). Let me know if you need some help :)

**Comment by avillarubia** [comment]
@koushik-radhakrishan thank you. I will try this
