### ISSUE TITLE
Error with Froala and Ember 3.4

### ISSUE THREAD

**Issue by raphaelns-developer** [froala/ember-froala-editor#68]
I updated my addon to Ember 3.4.0, but now the ember-froala-editor is throwing an error when i trie to start the dummy app:
```js
froala_editor.min.js:6 Uncaught TypeError: Cannot read property 'fn' of undefined
    at froala_editor.min.js:6
    at froala_editor.min.js:6
    at froala_editor.min.js:6
```

To make shure that is something related with the froala addon a created a new addon using ember-cli 3.4 and everything works fine, but after i addded the ember-froala-editor to the addon this error starts to occourr.

* I tested with versions 2.8.4 and 2.8.5

**Comment by Panman8201** [comment]
Humm... that's an error from the actual editor source, [imported from the froala-editor package](https://github.com/froala/ember-froala-editor/blob/v2.8.5/index.js#L84). What are your config options for the editor? I can try to replicate the issue but I'm going to guess that it's an upstream error.

**Comment by raphaelns-developer** [comment]
@Panman8201 Thanks for the help!
Actualy i'm not configuring any options on `environment.js` to Froala because it is just a dummy app from my addon. I have a component wich extend the FroalaEditor and override some options:
```js
lastFileName: null,

  options: computed('urlForUpload', function() {
    return {
      imageUploadParam: 'upload[file]',
      imageUploadURL: get(this, 'urlForUpload'),
      imageUploadMethod: 'POST',
      videoUploadParam: 'upload[file]',
      videoUploadURL: get(this, 'urlForUpload'),
      videoUploadMethod: 'POST',
      fileUploadParam: 'upload[file]',
      fileUploadURL: get(this, 'urlForUpload'),
      fileUploadMethod: 'POST',
      videoInsertButtons: ['videoBack', '|', 'videoByURL', 'videoEmbed']
    };
  }),

  'on-image-uploaded': (component, response) => {
    component.reinsertFile(response, 'image');

    return false;
  },

  'on-video-uploaded': (component, response) => {
    component.reinsertFile(response, 'video');

    return false;
  },

  'on-file-beforeUpload': (component, files) => {
    set(component, 'lastFileName', files[0].name);
  },

  'on-file-uploaded': (component, response) => {
    let { data: { upload: { url } } } = JSON.parse(response);

    component.send('method', 'file.insert', `${component.formatURL(url, 'file')}`, get(component, 'lastFileName'));

    return false;
  },

  reinsertFile(response, type) {
    let { data: { upload: { url } } } = JSON.parse(response);

    this.send('method', `${type}.remove`);

    this.send('method', `${type}.insert`, `${this.formatURL(url, type)}`);
  },

  formatURL(url, type) {
    let size = type === 'image' ? '0x0' : null;

    return formatUploadURL(get(this, 'environmentName'), get(this, 'assetHost'), url, size);
  }
```

But this error occurs when i start the application using `ember server` so i think that is something not related with this options.

**Comment by Panman8201** [comment]
Everything looks good there from the ember perspective. What happens when you comment out your `options` block? I'm guessing / hoping that the error goes away on `ember server`. Also, had you been successfully using this prior to 2.8.4 or is this a new project for you?

**Comment by raphaelns-developer** [comment]
I created a public project with Ember 3.4.3 and Froala 2.8.5. To reproduce the error download the project, start the ember and access the localhost, you will see the error printed in the browser' log.

https://github.com/raphaelns-developer/froala-editor-test

**Comment by Panman8201** [comment]
https://github.com/raphaelns-developer/froala-editor-test/blob/master/tests/dummy/config/optional-features.json#L2 

Needs to be `"jquery-integration": true` since Froala Editor still requires jQuery. (They, Froala, are working on a jQuery-less, module based update...)

**Comment by raphaelns-developer** [comment]
This option fix the issue. Thanks
