### ISSUE TITLE
Image size bigger than the container

### ISSUE THREAD

**Issue by dnstld** [froala/ember-froala-editor#69]
Hello.
I think there is a problem when some image is attached.

What I realized was that the attached image receives an inline style with the width property and when it's bigger than the parent container the image exceeds the container size.

I think, maybe, should have some max-width CSS property for image elements.

<img width="658" alt="screen shot 2018-10-02 at 09 30 21" src="https://user-images.githubusercontent.com/3258939/46348998-2d401a00-c627-11e8-9d6c-4c799d94b32a.png">

<img width="471" alt="screen shot 2018-10-02 at 09 31 07" src="https://user-images.githubusercontent.com/3258939/46348999-2dd8b080-c627-11e8-8717-6c8c6314f64b.png">

Thanks!

**Comment by Panman8201** [comment]
Hi @dnstld, I think this would be better posted over on the froala editor repo: https://github.com/froala/wysiwyg-editor/issues

**Comment by Panman8201** [comment]
Closing this for not since it doesn't seem to be ember addon specific, but rather for the actual editor itself. We can certainly re-open if you'd like to continue discussion.

**Comment by dnstld** [comment]
Thanks @Panman8201 👍🏼
