### ISSUE TITLE
Switch to ember-fontawesome

### ISSUE THREAD

**Issue by Panman8201** [froala/ember-froala-editor#70]
It seems development of [ember-font-awesome](https://github.com/martndemus/ember-font-awesome) has stalled, probably due to Fort Awesome making their own official addon for ember. [Look into switching over](https://github.com/froala/ember-froala-editor/blob/v2.8.5/package.json#L79) and [installing this by default for new users](https://github.com/froala/ember-froala-editor/blob/v2.8.5/blueprints/ember-froala-editor/index.js#L13).

https://github.com/FortAwesome/ember-fontawesome

**Comment by ShenglinGuo** [comment]
@Panman8201 
We are having issue where froala dependency of ember-font-awesome + fontawsome 4 is conflicting with fortawesome/ember-fontawsome . Before your 3.0 release, is there any temporary workaround to this problem? When will you likely to be releasing the 3.0 version?

Thank you

**Comment by Panman8201** [comment]
@ShenglinGuo this addon doesn't enforce that dependency, it actually [adds the dependency to the consuming project](https://github.com/froala/ember-froala-editor/blob/v2.9.0/blueprints/ember-froala-editor/index.js#L13). So, you should be able to `npm uninstall ember-font-awesome --save`.

**Comment by ShenglinGuo** [comment]
@Panman8201 
Thank you, I have actually already done that and found a work around,
basically
- manually remove ember-font-awsome
- add reference to fontawsome css in the index.html (CDN)

works fine, Thanks

**Comment by Panman8201** [comment]
Since Froala Editor v3 has moved away from FontAwesome, I'm closing this case as the dependency for ember-font-awesome will be removed entirely.
