### ISSUE TITLE
Image upload question

### ISSUE THREAD

**Issue by atuldhanorker** [froala/ember-froala-editor#72]
This is just a How to questions. I have added ImageUploadURL in the default options but do not see a request to a server when I upload the image. Any help with image upload is appreciated.

`import FroalaEditorComponent from 'ember-froala-editor/components/froala-editor';
export default FroalaEditorComponent.extend({
  defaultOptions: {
    key: '',
    imageUploadURL: '/api/teachingBlog/index.php/uploadImageTest',
    theme : 'red'
  }
});`

**Comment by Panman8201** [comment]
The `defaultOptions` changed to just `options` some time ago. Depending on the version of this addon you're using, that could be the issue. Are there any errors in the console upon inserting an image?

```js
import FroalaEditorComponent from 'ember-froala-editor/components/froala-editor';
export default FroalaEditorComponent.extend({
    options: {
        key: '',
        imageUploadURL: '/api/teachingBlog/index.php/uploadImageTest',
        theme : 'red'
    }
});
```

**Comment by atuldhanorker** [comment]
Thanks for quick response. I changed it to options and it worked. Also, I created a new custom button. Any suggestion to add it to toolbar list.
https://www.froala.com/wysiwyg-editor/examples/custom-buttons

**Comment by Panman8201** [comment]
At this point the best option is to use an application initializer in ember. After that it should be ready to include in your editor toolbar.

http://www.emberwysiwygeditor.com/#/addon/concepts?section=custom

**Comment by Panman8201** [comment]
Closing this for now. If you have any follow-up questions just comment here and I can re-open. Thanks
