### ISSUE TITLE
Support for custom @tagName

### ISSUE THREAD

**Issue by Panman82** [froala/ember-froala-editor#74]
With the move to Glimmer Components, the Ember Component `tagName` property/option does not apply. There is a [Dynamic tag names RFC](https://github.com/emberjs/rfcs/blob/master/text/0389-dynamic-tag-names.md) that has been accepted but not implemented yet. Additionally, I'd like to wait for the [Add new basic helpers to Ember RFC](https://github.com/emberjs/rfcs/pull/388) to land so that we can keep `<FroalaContent />` as a template-only component. Eg: `{{#let (element (or @tagName "div") as |Tag|}}`

**Comment by Panman8201** [comment]
Forgot to mention, the `(or @tagName "div")` could instead be `(if @tagName @tagName "div")`, inline if, so the basic helpers RFC isn't needed necessarily.

**Comment by Panman8201** [comment]
FWIW, could use [`ember-element-helper`](https://github.com/tildeio/ember-element-helper) but blocked on an [issue with modifiers](https://github.com/tildeio/ember-element-helper/issues/6).

**Comment by Panman82** [comment]
Looks like we'll have to reduce back-compat (currently 3.4+) to get `@tagName` support due to a glimmer-vm issue with modifiers prior to ember 3.7.2 (see the "issues with modifiers" link above).

**Comment by Panman82** [comment]
So there has been zero movement on this from the Ember front. There are three options we can take with this addon;

1. Continue to wait for the built-in `{{element}}` helper and polyfill
2. Use the `ember-element-helper` addon and reduce backwards compat to 3.7.2+
3. Drop the idea of supporting `@tagName` since the `<div>` variant is probably the best option for ember.js

Taking votes or other ideas. 😄

**Comment by Panman82** [comment]
At this point we'll go with option 3 of not supporting a custom `@tagName` since there still is no movement here on the ember front, and additionally the `ember-element-helper` addon outputs a custom Ember Component instead of a Glimmer Component (which negates any perf improvements). Will close for now but post here if you need support and we can discuss again. Thanks
