### ISSUE TITLE
can't customize toolbar button list in froala-editor declaration

### ISSUE THREAD

**Issue by BMahabir** [froala/ember-froala-editor#75]
When I try to customize the toolbar buttons in a meaningful way, it simply does not work.  When I declare `{{froala-editor content=etc ... }}` with no `toolbarButtons` parameter, I get a perfectly-formatted display of every button of every type that I have imported :  

![image](https://user-images.githubusercontent.com/1659720/59056200-a8686880-8865-11e9-840c-df02d7dd2793.png)  

Then, when I cherry pick just a few and define `{{froala-editor content=etc toolbarButtons=buttonList}}` in a template with `buttonList: ['bold', 'italics', 'underline']` in the JS, then that works great too : 

![image](https://user-images.githubusercontent.com/1659720/59056370-085f0f00-8866-11e9-9650-88efd4b66d1e.png)  

But when I try to actually do something useful like having the same template with 

```
buttonList: {
    'moreText': {
      'buttons': ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', 'textColor', 'backgroundColor', 'inlineClass', 'inlineStyle', 'clearFormatting']
    },
    'moreParagraph': {
      'buttons': ['alignLeft', 'alignCenter', 'formatOLSimple', 'alignRight', 'alignJustify', 'formatOL', 'formatUL', 'paragraphFormat', 'paragraphStyle', 'lineHeight', 'outdent', 'indent', 'quote']
    },
    'moreRich': {
      'buttons': ['insertLink', 'insertImage', 'insertVideo', 'insertTable', 'emoticons', 'fontAwesome', 'specialCharacters', 'embedly', 'insertFile', 'insertHR']
    },
    'moreMisc': {
      'buttons': ['undo', 'redo', 'fullscreen', 'print', 'getPDF', 'spellChecker', 'selectAll', 'html', 'help']
    }
  } 
```

in the JS, it produces nothing at all :  

![image](https://user-images.githubusercontent.com/1659720/59056529-6b50a600-8866-11e9-82fb-dd1a11131781.png)  

I wish I had some clue of what I'm doing wrong.  Thanks for your help and taking the time to read this.

**Comment by BMahabir** [comment]
It turns out, the cherry-picking method, in combination with `-` and `|`, is all that's really needed after all.

**Comment by divyanshu-rawat** [comment]
@BMahabir I am also facing the same problem, above mentioned grouping is not working, do you know any workaround for the same?

**Comment by BMahabir** [comment]
> @BMahabir I am also facing the same problem, above mentioned grouping is not working, do you know any workaround for the same?

Just choose each item individually, like I said in the comment from 23 days ago, and separate them  with `-` for a new line or `|` for a new section within the same line.
