### ISSUE TITLE
ember-froala-editor is not working on ios

### ISSUE THREAD

**Issue by krnbatta** [froala/ember-froala-editor#8]
On IOS(iphone or ipad, any version), when i click on the froala div, it don't get focused. It only gets focused when i click Bold or italic or any other tool that involves focusing in the toolbar.

**Comment by Panman8201** [comment]
Were you able to resolve this issue? It works for my project on iOS 9.

**Comment by mike183** [comment]
Also appears to be working fine for my project on iOS9.

**Comment by Panman8201** [comment]
Closing for now. Please post back if you continue to have troubles.
