### ISSUE TITLE
Errors caused by spell check plugin

### ISSUE THREAD

**Issue by dbollinger** [froala/ember-froala-editor#83]
I will try to recreate the issue and share more details later, but wanted to create this issue just in case anybody else is experiencing it.

I've been testing out latest beta release (3.0.0-beta.4) and one issue I'm encountering occasional and seemingly random console errors with the spell check plugin.  Mt assumption is that there's an async or teardown issue, but I haven't had time to dig in much further. 

I have one ember test in my app that just renders the editor in a wrapper component and nothing else, and it sometimes fails with an error like `can't read length of undefined` from somewhere in spell_checker.js.  I also occasionally saw the error while running my actual application.

Overall, everything seems really great, and I'm not actually using the spell check plugin in my application, so the current state feels just about production-ready to me 😄

Thanks for the updates!

**Comment by Panman82** [comment]
Interesting. I've run into errors a few times that were coming upstream from the [froala-editor](https://github.com/froala/wysiwyg-editor) itself. But, it could be a timing thing with the ember/glimmer component lifecycle. A stacktrace should help figure that out if you've got that.

**Comment by Panman82** [comment]
Just checking in here. Any more details @dbollinger? Also, just released `3.1.0-beta.5` which may help... Although I don't see anything in the changelog talking about the spell check plugin.

**Comment by Panman82** [comment]
Hi @dbollinger, I'm going to close this issue for now but if you get time to dig-in or discuss feel free to post back here and I can certainly re-open this issue. Thx!
