### ISSUE TITLE
Image and File Editor Support

### ISSUE THREAD

**Issue by Panman82** [froala/ember-froala-editor#88]
I see that with v3.2 there is a new image/file manager tool. Need to do some checking on if anything is needed here, such as a new component. I'd also like to get this out of beta so I'll find some time here get things going again. EDIT: Probably September or October at this point, I work for a school district and we're getting ready for the upcoming year ATM.

**Comment by fran-worley** [comment]
Having looked at the source code for the image manager plugin, it really isn't very ember friendly particularly in respect of loading the images. It seems to be using a jquery AJAX request (even though jQuery was removed??!). Modern ember has moved away from these in favour of ember-fetch, and if your app uses ember-data it seems sensible to make use of the store to grab images?

I don't know to what extend this app intends to provide an ember optimised version of froala-editor or a just simple way to get froala-editor to work in an ember app.

**Comment by Panman82** [comment]
Yeah, a bit disappointing about jQuery, I've noticed some jQuery remnants too. I think they just bundle-in whatever is needed instead of truly rewriting the DOM manipulation stuff and such.

Yeah, so far it's just provided ember integrations as best as possible, nothing rewritten for ember specifically. I still haven't taken a look at the image manager myself, so thanks for checking. This might be a case where the library provided solution just won't work well with the framework. 🤷‍♂️

**Comment by Panman82** [comment]
Since the new image manager is an editor plugin, there is nothing additional to do here.
