### ISSUE TITLE
Editor doesn't show content when extending from FroalaEditorComponent

### ISSUE THREAD

**Issue by hok** [froala/ember-froala-editor#9]
The editor works fine when using the froala-editor component directly but does not show current content when extending from FroalaEditorComponent as suggested in 

http://froala.github.io/ember-froala-editor/#/addon/concepts

Entering new content works just fine when used directly or when extending.

**Comment by Panman8201** [comment]
Interesting, I'm extending the editor as show in the [Defaults example](http://froala.github.io/ember-froala-editor/#/addon/concepts?section=defaults). What version of ember are you using? We just [merged a PR for 2.8 support](https://github.com/froala/ember-froala-editor/pull/10) but haven't released just yet.

**Comment by mike183** [comment]
FWIW I'm currently extending the `froala-editor` component as shown in the [Defaults example](http://froala.github.io/ember-froala-editor/#/addon/concepts?section=defaults) and it seems to be working as expected.

**Comment by hok** [comment]
@Panman8201 I was using 2.7.2.

@mike183 that's weird. I'm trying to use froala in two ways: 

**Directly with the provided component:**
```
<label>Users profile
  {{froala-editor
    content=model.user.profile
    options=(hash heightMin=300)
  }}
</label>
```

**By creating a component as suggested in the example:**

```
<label>Users profile 2
  {{froala-comp
    content=model.user.profile
    options=(hash heightMin=300)
  }}
</label>
```

**The component is defined as:**

```
import FroalaEditorComponent from 'ember-froala-editor/components/froala-editor';

export default FroalaEditorComponent.extend({
  defaultOptions : {
    key   : 'ABC',
    theme : 'red'
  },

  'on-blur' : function() {
    console.log('BLURRING');
  }
});
```

and the component template has just the yield statement.

It seems to be related to this if statement:

https://github.com/froala/ember-froala-editor/blob/master/addon/components/froala-editor.js#L480

If I just move the line (L482)

`
editor.html.set( this.get('_content') );
`

outside of the if statement the content is displayed (although that might not be optimal otherwise).

**Comment by Panman8201** [comment]
> and the component template has just the yield statement.

Ah, you shouldn't overload the template, just delete your custom `*.hbs` template and it should work.

It's important that the component have control over the `content`. The Froala Editor changes the DOM itself so having Ember also change it when the content changes can cause problems. That's why you can't use the `{{froala-editor}}` in block form.

**Comment by hok** [comment]
@Panman8201 oh cool, it works now :) Thank you!

**Comment by Panman8201** [comment]
Great! I'm going to close the issue then since it's working.
