### ISSUE TITLE
Fix on Portuguese transalation

### ISSUE THREAD

**Issue by GabrielSystemar** [froala/ember-froala-editor#90]
Hi, i am using the froala editor with portuguese language configuration

i finded three little mistakes in the translation:
- there is missing translations for "Text Color" ("Cor de texto")
- Italic translation is wrong the right translation is "Itálico" not "Itálito"
- More Rich translation is also wrong the right translation is "Mais detalhes" not "Mais Rico"

if there is a way for overwrite the translation i would be glad to know, or just fix this on the next release

thanks for any help

**Comment by Panman82** [comment]
Hi @GabrielSystemar, this repo is for the ember integration specifically. The actual editor (and language files) come from the wysiwyg-editor repo, I'd suggest opening this issue over there. Thanks! https://github.com/froala/wysiwyg-editor/issues
